baseURL = "https://ric-unknownartist.projektemacher.org/"
languageCode = "en"
title = "Ric - An unknown artist"
publishDir = "docs"
canonifyurls = true
languagecode = "en"
defaultcontentlanguage = "en"
DefaultContentLanguage = "en"
disablePathToLower = false
theme = ["observer-hugo"]
timeout = 120000
enableGitInfo = true

[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
                name = "Home"
                weight = 1
                url = "/"

            [[languages.en.menu.main]]
                name = "Ric"
                weight = 2
                url = "ric/"

            [[languages.en.menu.main]]
                name = "Further hints"
                weight = 3
                url = "hints/"

            [[languages.en.menu.main]]
                name = "Known works"
                weight = 4
                url = "works/"

            [[languages.en.menu.main]]
                name = "Map"
                weight = 5
                url = "map/"

            [[languages.en.menu.main]]
                name = "About"
                weight = 6
                url = "about/"


    [languages.de]
        languagename = "Deutsch"

        [languages.de.params]

        [languages.de.menu]

            [[languages.de.menu.main]]
                name = "Home"
                weight = 1
                url = "/"

            [[languages.de.menu.main]]
                name = "Ric"
                weight = 2
                url = "ric/"

            [[languages.de.menu.main]]
                name = "Further hints"
                weight = 3
                url = "hints/"

            [[languages.de.menu.main]]
                name = "Known works"
                weight = 4
                url = "works/"

            [[languages.de.menu.main]]
                name = "Map"
                weight = 5
                url = "map/"

            [[languages.de.menu.main]]
                name = "About"
                weight = 6
                url = "about/"

[markup]
  defaultMarkdownHandler = 'goldmark'

[markup.goldmark]
    duplicateResourceFiles = true

    [markup.goldmark.renderer]
        unsafe = true

    [markup.goldmark.extensions]
        attribute = true
        strikethrough = true

  [markup.goldmark.extensions.typographer]
          apostrophe = '&rsquo;'
          disable = false
          ellipsis = '&hellip;'
          emDash = '&mdash;'
          enDash = '&ndash;'
          leftAngleQuote = '&laquo;'
          leftDoubleQuote = '&ldquo;'
          leftSingleQuote = '&lsquo;'
          rightAngleQuote = '&raquo;'
          rightDoubleQuote = '&rdquo;'
          rightSingleQuote = '&rsquo;'

  [markup.goldmark.extensions.extras]
      [markup.goldmark.extensions.extras.insert]
          enable = true
      [markup.goldmark.extensions.extras.mark]
          enable = true
      [markup.goldmark.extensions.extras.subscript]
          enable = true
      [markup.goldmark.extensions.extras.superscript]
          enable = true

[imaging]
    quality = 95

[sitemap]
  changeFreq = 'weekly'

[module]
    [[module.mounts]]
        source = "assets/scss"
        target = "assets/scss"

    [[module.mounts]]
        source = "static"
        target = "static"

    [[module.mounts]]
        source = "node_modules/lightgallery"
        target = "assets/js/lightgallery"

    [[module.mounts]]
        source = "node_modules/lightgallery/css"
        target = "assets/css/lightgallery"

    [[module.mounts]]
        source = "node_modules/lightgallery/fonts"
        target = "static/fonts/lightgallery"

    [[module.mounts]]
        source = "node_modules/lightgallery/images"
        target = "static/images/lightgallery"

[build]
  writeStats = true

[taxonomies]
  tag = "tags"
