baseURL = "https://ric-unknownartist.projektemacher.org/"
languageCode = "en"
title = "Ric - An unknown artist"
publishDir = "docs"
canonifyurls = true
languagecode = "en"
defaultcontentlanguage = "en"
disablePathToLower = true
theme = "observer-hugo"

[params]
author = "Christian Mahnke"
keywords = "Ric, artist, unknown, Fritz Neumann, JCB"
description = "This blog tries to help to solve the mystery „Who was Ric?“"
logo = "/images/logo.png"
svgIcon = "/images/favicon.svg"
stylesheets = ["https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap"]
linkTumblr = true
hideTitle = true
widePosts = true
enableImageViewer = true
enablePDFViewer = false

[menu]
    [[menu.main]]
        name = "Home"
        weight = 1
        url = "/"

    [[menu.main]]
        name = "Ric"
        weight = 2
        url = "ric/"

    [[menu.main]]
        name = "Further hints"
        weight = 3
        url = "hints/"

    [[menu.main]]
        name = "Known works"
        weight = 4
        url = "works/"

    [[menu.main]]
        name = "Map"
        weight = 5
        url = "map/"

    [[menu.main]]
        name = "About"
        weight = 6
        url = "about/"

[markup.goldmark.renderer]
    unsafe= true

[module]
    [[module.mounts]]
        source = "assets/scss"
        target = "assets/scss"

    [[module.mounts]]
        source = "static"
        target = "static"

    [[module.mounts]]
        source = "node_modules/lightgallery/dist/js"
        target = "assets/js/lightgallery"

    [[module.mounts]]
        source = "node_modules/lightgallery/dist/css"
        target = "assets/css/lightgallery"

    [[module.mounts]]
        source = "node_modules/lightgallery/dist/fonts"
        target = "static/fonts/lightgallery"

    [[module.mounts]]
        source = "node_modules/lightgallery/dist/img"
        target = "static/images/lightgallery"
